name: Android CI (Debug/Release + optional Firebase)

on:
  workflow_dispatch:
    inputs:
      releaseNotes:
        description: "Optional release notes (used if you enable Firebase step)"
        required: false
        default: "Manual build"
  # Uncomment below if you want to auto-run later
  # push:
  #   tags:
  #     - 'v*'      # e.g. v1.0.0
  #   branches:
  #     - main
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configure Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        # Note: This is unsigned unless you configure signingConfigs.release in Gradle
        run: ./gradlew :app:assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      # Optional: Build Release AAB (Play-ready bundle)
      # - name: Build Release AAB
      #   run: ./gradlew :app:bundleRelease
      # - name: Upload Release AAB
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-aab
      #     path: app/build/outputs/bundle/release/app-release.aab

      # Optional: Firebase App Distribution (requires Gradle plugin + FIREBASE_TOKEN secret)
      # Enable after you add the plugin in app/build.gradle.kts and set repository secret FIREBASE_TOKEN
      # - name: Upload to Firebase App Distribution (Release)
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: |
      #     ./gradlew :app:assembleRelease :app:appDistributionUploadRelease \
      #       -PfirebaseAppDistribution.groups=internal \
      #       -PfirebaseAppDistribution.releaseNotes="${{ github.event.inputs.releaseNotes }}"

name: Android CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug
        run: ./gradlew assembleDebug --no-daemon --stacktrace --console=plain

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace --console=plain
